import { geminiService } from '@/services/geminiService';
import { approximateISLGloss } from './islGrammarRules';
import { SignAssetRegistryService } from '@/modules/sign-output/SignAssetRegistry';
import { GlossToken, GlossTranslationResult, GlossTranslationSource } from '@/types/isl';
import { isFeatureEnabled } from '@/config/featureFlags';

export class ISLGlossEngine {
  private static instance: ISLGlossEngine;

  public static getInstance(): ISLGlossEngine {
    if (!ISLGlossEngine.instance) {
      ISLGlossEngine.instance = new ISLGlossEngine();
    }
    return ISLGlossEngine.instance;
  }

  /**
   * Main Translation Pipeline:
   * English Text -> Normalization -> Gemini (Optional) -> Local Fallback -> Sign Tokens -> Asset Resolver
   */
  public async translateTextToGloss(inputText: string): Promise<GlossTranslationResult> {
    const trimmed = inputText.trim();
    if (!trimmed) {
      return {
        sourceText: '',
        tokens: [],
        source: 'rule-based-fallback',
        confidence: 0,
        linguisticNotes: [],
        isFallback: false,
      };
    }

    let rawTokens: string[] = [];
    let notes: string[] = [];
    let source: GlossTranslationSource = 'rule-based-fallback';
    let confidence = 0.85;
    let isFallback = false;
    let fallbackReason: string | undefined;

    // 1. Try Gemini NLP layer if enabled and configured
    if (isFeatureEnabled('enableGemini') && geminiService.isAvailable()) {
      try {
        const geminiResult = await geminiService.translateToISLGloss(trimmed, 1);
        rawTokens = geminiResult.gloss;
        notes = [
          'Generated by Google Gemini ISL NLP layer (SOV alignment, temporal fronting, WH-movement).',
          geminiResult.notes,
        ].filter(Boolean);
        source = 'gemini';
        confidence = geminiResult.confidence;
        isFallback = false;
      } catch (err: unknown) {
        const errMsg = err instanceof Error ? err.message : String(err);
        console.warn('[ISL Gloss Engine] Gemini request failed, activating local fallback:', errMsg);

        fallbackReason = `Gemini API: ${errMsg}. Local ISL grammar rules active.`;
        const localFallback = approximateISLGloss(trimmed);
        rawTokens = localFallback.tokens;
        notes = [
          `Gemini unavailable (${errMsg}). Fallback to local ISL linguistic heuristic.`,
          ...localFallback.notes,
        ];
        source = localFallback.isExactPhraseMatch ? 'phrase-dictionary' : 'rule-based-fallback';
        confidence = localFallback.isExactPhraseMatch ? 0.95 : 0.82;
        isFallback = true;
      }
    } else {
      // 2. Local fallback engine (phrase dictionary + grammar rules)
      const localResult = approximateISLGloss(trimmed);
      rawTokens = localResult.tokens;
      source = localResult.isExactPhraseMatch ? 'phrase-dictionary' : 'rule-based-fallback';
      confidence = localResult.isExactPhraseMatch ? 0.98 : 0.85;
      isFallback = false;

      if (localResult.isExactPhraseMatch) {
        notes = [
          'Matched verified entry in ISL Phrase Dictionary.',
          ...localResult.notes,
        ];
      } else {
        notes = [
          'Processed using local ISL grammar engine (Gemini API disabled or unconfigured in .env).',
          ...localResult.notes,
        ];
      }
    }

    // 3. Resolve sign tokens to visual assets via SignAssetRegistryService
    const finalTokens: GlossToken[] = [];

    for (let i = 0; i < rawTokens.length; i++) {
      const raw = rawTokens[i].toUpperCase().trim();
      if (!raw) continue;

      // Handle FS(...) pattern (named entities or unknown terms)
      const isExplicitFs = raw.startsWith('FS(') && raw.endsWith(')');
      const tokenName = isExplicitFs ? raw.slice(3, -1) : raw;

      const matchedAsset = SignAssetRegistryService.getAsset(tokenName);

      if (matchedAsset && !isExplicitFs) {
        finalTokens.push({
          id: `token-${i}-${tokenName}`,
          originalWord: tokenName,
          gloss: tokenName,
          matchedAsset,
          isFingerspelled: false,
        });
      } else {
        // Fall back to fingerspelling character-by-character
        const letters = tokenName.replace(/[^A-Z0-9]/g, '').split('');
        if (letters.length > 0) {
          for (let j = 0; j < letters.length; j++) {
            const letter = letters[j];
            const letterAsset = SignAssetRegistryService.getAsset(letter);
            finalTokens.push({
              id: `token-${i}-fs-${j}-${letter}`,
              originalWord: tokenName,
              gloss: letter,
              matchedAsset: letterAsset,
              isFingerspelled: true,
              note: j === 0 ? `Fingerspelled: ${tokenName}` : undefined,
            });
          }
        }
      }
    }

    return {
      sourceText: trimmed,
      tokens: finalTokens,
      source,
      confidence,
      linguisticNotes: notes,
      isFallback,
      fallbackReason,
    };
  }
}

export const islGlossEngine = ISLGlossEngine.getInstance();
